# Generated by Django 4.1.1 on 2022-09-29 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0002_rename_descriptin_site_setting_description_site'),
    ]

    operations = [
        migrations.RenameField(
            model_name='setting',
            old_name='adress_site',
            new_name='address_site',
        ),
    ]
