# Generated by Django 4.1.1 on 2022-10-01 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0005_aboutus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutus',
            name='video_url',
            field=models.FileField(upload_to='video/'),
        ),
    ]
