# Generated by Django 4.1.1 on 2022-10-08 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0007_team'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_news', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image_news', models.ImageField(upload_to='image_news/')),
                ('created_news', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
            },
        ),
    ]
