# Generated by Django 4.1.2 on 2022-10-31 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0009_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='age',
            field=models.PositiveSmallIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team',
            name='availability',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team',
            name='experience',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team',
            name='language',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
